### ISSUE TITLE
ValueError: could not broadcast input array from shape (3,2048) into shape (6144)

### ISSUE THREAD

**Issue by carlosvega** [plaidml/plaidvision#14]
I tried to use plaidvision on MacOS High Sierra 10.13.6 (17G65) with a MacBook 15'' Intel Iris Pro 1536 MB and I got the following error:

```
python ./plaidvision.py --plaid mobilenet
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Using PlaidML backend.
INFO:plaidml:Opening device "opencl_intel_iris_pro.0"
Traceback (most recent call last):
  File "./plaidvision.py", line 314, in <module>
    main()
  File "./plaidvision.py", line 264, in main
    model = Model(args.model, args.weights)
  File "./plaidvision.py", line 206, in __init__
    self.model = ModelClass(weights=weights)
  File "/Users/carlosvega/plaidml-venv/lib/python3.6/site-packages/keras/applications/mobilenet.py", line 449, in MobileNet
    x = _conv_block(img_input, 32, alpha, strides=(2, 2))
  File "/Users/carlosvega/plaidml-venv/lib/python3.6/site-packages/keras/applications/mobilenet.py", line 586, in _conv_block
    name='conv1')(inputs)
  File "/Users/carlosvega/plaidml-venv/lib/python3.6/site-packages/keras/engine/topology.py", line 575, in __call__
    self.build(input_shapes[0])
  File "/Users/carlosvega/plaidml-venv/lib/python3.6/site-packages/keras/layers/convolutional.py", line 134, in build
    constraint=self.kernel_constraint)
  File "/Users/carlosvega/plaidml-venv/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/Users/carlosvega/plaidml-venv/lib/python3.6/site-packages/keras/engine/topology.py", line 396, in add_weight
    weight = K.variable(initializer(shape),
  File "/Users/carlosvega/plaidml-venv/lib/python3.6/site-packages/keras/initializers.py", line 212, in __call__
    dtype=dtype, seed=self.seed)
  File "/Users/carlosvega/plaidml-venv/lib/python3.6/site-packages/plaidml/keras/backend.py", line 1238, in random_uniform
    rng_state = _make_rng_state(seed)
  File "/Users/carlosvega/plaidml-venv/lib/python3.6/site-packages/plaidml/keras/backend.py", line 170, in _make_rng_state
    rng_state = variable(rng_init, dtype='uint32')
  File "/Users/carlosvega/plaidml-venv/lib/python3.6/site-packages/plaidml/keras/backend.py", line 1762, in variable
    view.copy_from_ndarray(value)
  File "/Users/carlosvega/plaidml-venv/lib/python3.6/site-packages/plaidml/__init__.py", line 1194, in copy_from_ndarray
    np.copyto(dst, src)
ValueError: could not broadcast input array from shape (3,2048) into shape (6144)
```

I tried with all these devices from plaidml-setup: 
>    1 : opencl_intel_iris_pro.0
>    2 : opencl_cpu.0
>    3 : llvm_cpu.0
>    4 : metal_intel_iris_pro_graphics.0

**Comment by tzerrell** [comment]
This appears to be the same issue as in [plaidml/plaidml issue #149](https://github.com/plaidml/plaidml/issues/149). We're working on putting together a release that will have a fix, but meanwhile you can use @mzeug 's fix from that issue (if you try that and it doesn't work please let us know so we can look for a different root problem).

**Comment by tzerrell** [comment]
PlaidML v0.3.5 is now out, which should fix this.
